project:
  type: website

website:
  title: "My Penguin Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: visualization.qmd
        text: Single Trait
      - href: multiple_traits.qmd
        text: Multiple Traits
      - href: sexual_dimorphism.qmd
        text: Sexual Dimorphism

format:
  html:
    theme: cosmo


